---
title: "Untitled"
author: "mdt-ds"
date: "11/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load("recipes")

```

## data

```{r}
dat <- readr::read_csv("dat.csv")
str(dat)
```

```{r}
d <- dat %>% 
   filter_all(any_vars(. == 9 ))
```

## preprocessing
```{r}
library(dplyr)
library(tidyr)
library(recipes)

factors <- c("SEQN","SLQ040","HSD010","DLQ140","HOD050","DBQ197","DLQ130","DLQ170","DBQ235C","DLQ110","DLQ100","DLQ150","DBQ700","SLQ050","PFQ063B","DPQ030","PFQ051","PFQ061N","PFQ061T","PFQ063A")




contn <- c("PHAFSTMN","LBXPLTSI","PHAFSTHR","LBDPCT","LBDTIB","LBXUIB","LBXIRN","LBDHDD","DSDCOUNT","DBD900","DBD905","DBD910","DBD895","WHQ150","WHD120","WHD010","WHD020","WHD050","WHD110","VTD271B","OCQ180","OCD270","OCD395","PAQ625","PAD630","PAQ670","PAD675","PAD680","WHD140","WHD130","DUQ220Q")

#reformat data

sleep_tbl <- dat %>%
drop_na(SLQ050) %>%
mutate_at(factors, factor) %>%
mutate_at(contn, as.numeric)

str(sleep_tbl)



```

## spend data
```{r}
library(rsample)
sleep_splits <- initial_split(data = sleep_tbl, strata = SLQ050, prop = 0.80)
sleep_train <- training(sleep_splits)
sleep_test <- testing(sleep_splits)
```

## preprocessing
```{r}
sleep_rec <- recipe(x = sleep_train, formula = SLQ050~.) %>% 
  update_role(SEQN, new_role = "ID") %>% 
  step_other(all_nominal_predictors(), threshold = 0.02) %>% 
  step_impute_mode(all_nominal_predictors()) %>% 
  step_impute_median(all_numeric_predictors()) %>% 
  step_nzv(all_predictors()) %>% 
  step_corr(all_numeric_predictors(),threshold = 0.8) %>% 
  prep()

sleep_rec
```

```{r}
sleep_train_baked <- bake(sleep_rec, sleep_train)
sleep_test_baked <- bake(sleep_rec, sleep_test)
```

## variable importance
```{r fig.height=8}
library(randomForest)
rfvi_mdl <- randomForest(SLQ050~., data = sleep_train_baked %>% select(-SEQN))
varImpPlot(rfvi_mdl)
selected_vars <- importance(rfvi_mdl) %>%  
  as_tibble( rownames = "variable") %>% 
  arrange (desc(MeanDecreaseGini)) %>% 
  slice_head(n = 20) %>% 
  pull(variable)
final_dat <- selected_vars

```


```{r}
library(ggplot2)
# DLQ110 Are you taking anxiety pills?
# DLQ140 How often do you fel depressed?
ggplot(sleep_tbl, aes(x = SLQ050, fill= DLQ110)) +
           geom_bar()

ggplot(data = sleep_tbl) + 
  geom_bar(mapping = aes(x = DLQ140, y = ..prop.., group = SLQ050), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) +
  facet_wrap(~SLQ050)

logit <- glm(SLQ050 ~ DLQ140, data = sleep_tbl, family = "binomial")
summary(logit)
```

```{r}
# HOD050 Number of rooms?
# Remove!
ggplot(data = sleep_tbl) + 
  geom_bar(mapping = aes(x = HOD050, y = ..prop.., group = SLQ050), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) +
  facet_wrap(~SLQ050)
```

```{r}
# BMXBMI - BMI
ggplot(data = sleep_tbl) + 
  geom_boxplot(mapping = aes(x = SLQ050, y = BMXBMI))

logit <- glm(data = sleep_tbl, SLQ050 ~ BMXBMI, family = "binomial")
summary(logit)
```
```{r}
# PFQ061T - push or pull large object
ggplot(data = sleep_tbl) + 
  geom_bar(mapping = aes(x = PFQ061T, y = ..prop.., group = SLQ050), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) +
  facet_wrap(~SLQ050)

logit <- glm(data = sleep_tbl, SLQ050 ~ PFQ061T, family = "binomial")
summary(logit)
```
```{r}
# DLQ150 
# Do you take medication for depression?

sleep_tbl$SLQ050 = factor(sleep_tbl$SLQ050, levels=c(1,2), labels=c("Yes","No"))
logit <- glm(data = sleep_tbl, SLQ050 ~ DLQ150 + DLQ140 + DLQ150 * DLQ140, family = "binomial")
summary(logit)
```

```{r}
# Health problem?
# Discard! No healthy option
logit <- glm(data = sleep_tbl, SLQ050 ~ PFQ063A, family = "binomial")
summary(logit)

# Limit in amount of work?
logit <- glm(data = sleep_tbl, SLQ050 ~ PFQ051, family = "binomial")
summary(logit)
```

```{r}
# age
logit <- glm(data = sleep_tbl, SLQ050 ~ age, family = "binomial")
summary(logit)

plot(logit)

ggplot(data = sleep_tbl) + 
  geom_bar(mapping = aes(x = age, y = ..prop.., group = SLQ050), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) +
  facet_wrap(~SLQ050)

young <- sleep_tbl %>% filter(age <= 60)
old <- sleep_tbl %>% filter(age > 60)

sleep_tbl$age1 <- ifelse(sleep_tbl$age >= 60, 0, 1)

logit <- glm(data = sleep_tbl, SLQ050 ~ age1, family = "binomial")
summary(logit)
```

```{r}
# SLQ040
logit <- glm(data = sleep_tbl, SLQ050 ~ SLQ040, family = "binomial")
summary(logit)
```

