---
title: "NHANES: What affects our sleep?"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: "sandstone" # or"yeti"
runtime: shiny

---

```{r global, include=FALSE}
pacman::p_load(
    rio,
    here,
    dplyr,
    tidyverse,
    flexdashboard,
    shiny,
    plotly,
    summarytools,
    prettycode
)

# import data
dat <- load(file = "ready.rda")
final_dat <- dat1
```

# Exploratory Data Analysis
Inputs {.sidebar}
-----------------------------------------------------------------------

On average, humans spend about a 1/3 of each day sleeping. Good sleep is not only vital to our day-to-day functioning but also allows us to lead healthy lives. In the US, 50-70 million people suffer from insomnia. This dashboard uses the 2018 NHANES data to explore the different variables that can affect our sleep. 

Top 10 variables that affect sleep were identified using machine learning. Here, users can explore the data and run different machine learning models to learn about these variables in depth.


```{r}
# separate factors and numeric variables
var_factor <- final_dat %>% 
  select_if(is.factor)

var_factor <- colnames(var_factor)

var_numeric <- final_dat %>% 
  select_if(is.numeric)

var_numeric <- colnames(var_numeric[-1])

# shiny app input numeric
selectInput("x", label = "X", names(final_dat))
selectInput("y", label = "Y", c("none", names(final_dat)), names(final_dat)[[2]])

selectInput("color", "Color", c("none", var_factor))

```


App authors: Briha Ansari, MD., Feng-Chiao Lee, Tim Lee, MD.

Row
-----------------------------------------------------------------------
### Total N
```{r}
total <- nrow(final_dat)
valueBox(total, icon = "fa-users")
```

### Average sleep hours
```{r}
hours <- 7.6
valueBox(hours, icon = "fa-bed")
```

### % Trouble sleeping
```{r}
valueBox(scales::percent(.285), icon = "fa-exclamation-circle",
         color = "warning")
# gauge(28.5, min = 0, max = 100, symbol = "%")
```

Row
-----------------------------------------------------------------------
### Plot

```{r}
# get plot type
# 2 = both numeric
# 1 = one numeric, one non-numeric
# 0 = both non-numeric
# -1 = only one variable
plot_type <- reactive({
  if(input$y != "none")
    is.numeric(final_dat[[input$x]]) + is.numeric(final_dat[[input$y]])
  else
    -1
})

renderPlot({
  if (plot_type() ==2) {
    # 2 num = scatterplot
    p <- ggplot(final_dat, aes_string(input$x, input$y)) +
      geom_point(alpha = 0.5) +
      geom_smooth()

    # color change
    if (input$color != "none")
      p <- p + aes_string(color = input$color)
  } else if (plot_type() == 1) {
    # 1 num, 1 non-num = boxplot
    p <- ggplot(final_dat, aes_string(input$x, input$y)) +
      geom_boxplot()
    
    # fill change
    if (input$color != "none")
      p <- p + aes_string(fill = input$color)
  } 
  else if (plot_type() == 0 ) {
    # 2 non-num = heatmap
    temp_dat <- reactive(final_dat[, c(input$x, input$y)] %>% 
                           group_by(across()) %>% 
                           summarize(count = n())
                         )
    p <- ggplot(temp_dat(),
                mapping = aes_string(x = input$x, y = input$y, fill = "count")) +
      geom_tile()
  } else {
    # 1 var only = univariate plot
    p <- ggplot(final_dat, aes_string(x = input$x))
    
    if(is.numeric(final_dat[[input$x]]))
      p <- p + geom_histogram()
    else
      p <- p + geom_bar()
    
    # fill change
    if(input$color != "none")
      p <- p + aes_string(fill = input$color)
  }
  
  # add title
  if(plot_type() >= 0) {
    p <- p + labs(title = paste(input$y, "vs.", input$x))
  } else {
    p <- p + labs(title = paste("Distribution of", input$x))
  }
  
  # add styling
  p <- p +
    theme_bw() +
    theme(plot.title = element_text(size = rel(1.8), face = "bold", hjust = 0.5),
          axis.title = element_text(size = rel(1.2)))
  print(p)
})

```

# Logistic Regression
Inputs {.sidebar}
-----------------------------------------------------------------------
```{r datloading}
dat <- load("ready.rda")
dat<-ready
# shiny app input numeric

selectInput("depression", label = "depression: How often do you feel depressed?", 
    choices = list("Daily" = "Daily", "weekly" = "weekly", "monthly" = "monthly",'few_times_year'='few_times_year','never'='never'), 
    selected = "Daily")
numericInput("bmi", label = "bmi: Body Mass Index (kg/m^2)", value = 12,  min = 12, max = 90, step = 0.1)  
selectInput("difficult_move_objects", label = "difficult_move_objects: Difficulty moving large objects?", 
    choices = list("no" = "no", "some" = "some", "much" = "much",'unable'='unable','dont_do_this_activity'='dont_do_this_activity'), 
    selected = "no")

selectInput("snort", label = "snort:  How often do you snort or stop breathing?", 
    choices = list("never" = "never", "1-2/wk" = "1-2/wk","3-4/wk"="3-4/wk","5/wk"="5/wk"), 
    selected = "never")

sliderInput("crp", label = "crp: HS C-Reactive Protein (mg/L)?",
            min = 0, 
            max = round(max(dat$crp),2), 
            value =round(0,2),step =0.01)

selectInput("anxious", label = "anxious:  How often do you feel worried or anxious?", 
    choices = list("daily" = "daily", "monthly" = "monthly","few/yr"="few/yr","never"="never"), 
    selected = "daily")


sliderInput("iron_um_l", label = "iron_um_l - Iron frozen, Serum (umol/L)",
            min =0, 
            max = round(max(dat$iron_um_l),2), 
            value =round(0,2),step =0.01)
selectInput("age.cat2", label = "age.cat2: Your Age Range", 
    choices = list("19-35" = "19-35", "36-50" = "36-50","51-65"="51-65","above65"="above65"), 
    selected = "19-35")
selectInput("variable", label = "Choose the Variable effect probability", names(dat))
```

```{r reactive expression}
dat <- load("ready.rda")
dat<-ready
logitMod <- glm(formula = sleep_problems ~ depression  + bmi + difficult_move_objects +snort+crp+anxious+iron_um_l+ age.cat2,data = dat,family = binomial(link = "logit"))
```

```{r stepup, include =FALSE}
library(DT)
library(dplyr)
library(tidyverse)
library(plotly)
library(ggeffects)
library(splines)
library(titanic)
library(lmerTest)
library(ggiraphExtra)
library(ggplot2)
library(ggridges)
```
Row {data-height=350} 
-----------------------------------------------------------------------
### Variable Effect on Sleeping Problem
```{r histogram}
renderPlot({
  
ggpredict(logitMod, terms = input$variable ,fill=input$variable)%>%plot()

  })

```



Row {data-height=350}
--------------
### Chart A

```{r}

```



### Chart C

```{r}
renderValueBox({
  testdata <- data.frame(depression =factor(input$depression),
                       snort=factor(input$snort),
                       difficult_move_objects = factor(input$difficult_move_objects),
                       snort = factor(input$snort),
                       crp = input$crp,
                       iron_um_l = input$iron_um_l,
                       anxious = factor(input$anxious),
                       bmi=input$bmi,
                       age.cat2 = factor(input$age.cat2))
testdata$prob<- predict(logitMod, newdata=testdata, type="response")

valueBox(scales::percent(round(testdata$prob,2)), "Sleeping Problem %",icon = "fa-exclamation-circle",color = "warning")
})
```


# Random Forest
Inputs {.sidebar}
-----------------------------------------------------------------------

# XGBoost
Inputs {.sidebar}
-----------------------------------------------------------------------



