---
title: "NHANES: What affects our sleep?"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
pacman::p_load(
    rio,
    here,
    tidyverse,
    flexdashboard,
    shiny,
    plotly,
    summarytools
)

# import data
dat <- read_csv("sleep.csv") %>% as.data.frame()

# change to factor
dat$SLQ050 <- as.factor(dat$SLQ050)
dat$HSD010 <- as.factor(dat$HSD010)
dat$DLQ100 <- as.factor(dat$DLQ100)

dat <- setNames(dat, 
                c("Sequence number",
                  "Sleep trouble", 
                  "Waist circumference (cm)", 
                  "Age in yrs at screening", 
                  "BMI",
                  "CRP",
                  "Hours of sleep",
                  "Iron, frozen (ng/dL)",
                  "Mean cell Hg (pg)",
                  "General health condition",
                  "Anxiety"))

```

# Exploratory Data Analysis
Inputs {.sidebar}
-----------------------------------------------------------------------

On average, humans spend about a 1/3 of each day sleeping. Good sleep is not only vital to our day-to-day functioning but also allows us to lead healthy lives. In the US, 50-70 million people suffer from insomnia. This dashboard uses the 2018 NHANES data to explore the different variables that can affect our sleep. 

Top 10 variables that affect sleep were identified using machine learning. Here, users can explore the data and run different machine learning models to learn about these variables in depth.

*Chart A*
```{r}
# separate factors and numeric variables
var <- colnames(dat[-1])

var_factor <- dat %>% 
  select_if(is.factor)

var_factor <- colnames(var_factor)

var_numeric <- dat %>% 
  select_if(is.numeric)

var_numeric <- colnames(var_numeric[-1])

# shiny app input numeric
selectInput("var1", label = "Variable Y",
            choices = var_numeric, selected = var_numeric[[1]])

selectInput("var2", label = "Variable X",
            choices = var_numeric, selected = var_numeric[[1]])
```
*Chart B*
```{r}
# shiny app input factor
selectInput("var3", label = "Factor",
           choices = var_factor, selected = var_factor[[1]])
```


App authors: Briha Ansari, MD., Feng-Chiao Lee, Tim Lee, MD.


Row
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlot({
  x <- dat %>% select(input$var2) %>% unlist()
  y <- dat %>% select(input$var1) %>% unlist()
  ggplot(dat, aes(x, y)) +
    geom_point() +
    geom_smooth()
})
```

### Chart B

```{r}
renderPlot({
  x <- dat %>% select(input$var3) %>% unlist()
  ggplot(dat, aes(x)) +
    geom_bar()
})
```


Row
-----------------------------------------------------------------------
### Chart C 

```{r}
knitr::kable(descr(dat))
```

# Logistic Regression
Inputs {.sidebar}
-----------------------------------------------------------------------

# Random Forest
Inputs {.sidebar}
-----------------------------------------------------------------------

# XGBoost
Inputs {.sidebar}
-----------------------------------------------------------------------
